-- Add extended CS2 GSI fields to promo_frag_matches
ALTER TABLE promo_frag_matches 
  ADD COLUMN IF NOT EXISTS total_damage INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rounds_played INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bombs_planted INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bombs_defused INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS clutch_kills INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flash_kills INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS smoke_kills INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eco_kills INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS round_results JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS weapon_kills JSONB DEFAULT '{}'::jsonb;
