-- Add extended Dota 2 GSI fields to promo_frag_matches
ALTER TABLE promo_frag_matches 
  ADD COLUMN IF NOT EXISTS hero_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS denies INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gpm INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS xpm INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS net_worth INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wards_placed INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wards_destroyed INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dota_stats JSONB DEFAULT '{}'::jsonb;
