-- Add financial fields to shifts if they don't exist
ALTER TABLE shifts 
ADD COLUMN IF NOT EXISTS cash_income DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS card_income DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS expenses DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS report_comment TEXT,
ADD COLUMN IF NOT EXISTS report_data JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS template_id INTEGER;
