-- ADD TIME AND DAY CONSTRAINTS TO PROMO QUESTS
ALTER TABLE promo_quests ADD COLUMN IF NOT EXISTS available_days INTEGER[];
ALTER TABLE promo_quests ADD COLUMN IF NOT EXISTS time_start TIME;
ALTER TABLE promo_quests ADD COLUMN IF NOT EXISTS time_end TIME;
